label: Vote tag
status: ready
default: Stimmfreigabe
display:
  padding: 40px
context:
  label: 'â€”'
  aria-label: Abstimmungsempfehlung
  modifiers:
    - free
variants:
  - name: No
    context:
      label: nein
      modifiers:
        - no
  - name: Yes
    context:
      label: ja
      modifiers:
        - yes
  - name: Initiative
    context:
      label: initiative
      modifiers:
        - initiative
  - name: Counter Project
    context:
      label: gegenvorschlag
      modifiers:
        - counter-project
  - name: Free
    context:
      label: Stimmfreigabe
      modifiers:
        - free2
  - name: Blank
    context:
      label: Leer
      modifiers:
        - blank
