label: Social icon
status: ready
default: facebook
context:
  type: facebook
  link: '#'
  ariaLabel: post on facebook
variants:
  - name: bluesky
    context:
      type: bluesky
      ariaLabel: share on bluesky
  - name: email
    context:
      type: email
      ariaLabel: share by email
  - name: link
    context:
      type: link
      linkButton: yes
      ariaLabel: copy link
